INSERT INTO T_PLAYER VALUES (1,'Adnan');
INSERT INTO T_PLAYER VALUES (2,'Kanpur');
INSERT INTO T_PLAYER VALUES (3,'Lucknow');
INSERT INTO T_PLAYER VALUES (4,'Pasha');
INSERT INTO T_PLAYER VALUES (5,'Farzaneh');
INSERT INTO T_PLAYER VALUES (6,'Dayan');

INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 1,100,0,current_date,'Credit' , 1 );
INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 2,100,0,current_date,'Credit' , 1 );
INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 3,100,0,current_date,'Credit' , 1 );
INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 4,100,0,current_date,'Credit' , 1 );
INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 5,100,0,current_date,'Credit' , 1 );
INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 6,100,0,current_date,'Credit' , 1 );
INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 7,100,0,current_date,'Credit' , 1 );
INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 8,100,0,current_date,'Credit' , 1 );

