INSERT INTO T_PLAYER VALUES (1,'Adnan');
INSERT INTO T_PLAYER VALUES (2,'Kanpur');
INSERT INTO T_PLAYER VALUES (3,'Lucknow');
INSERT INTO T_PLAYER VALUES (4,'Pasha');
INSERT INTO T_PLAYER VALUES (5,'Dayan');

INSERT INTO T_ACCOUNT( ID, BALANCE, LAST_MODIFIED, PLAYER_ID) VALUES ( 1,0,current_date, 1 );
INSERT INTO T_ACCOUNT( ID, BALANCE, LAST_MODIFIED, PLAYER_ID) VALUES ( 2,0,current_date, 2 );
INSERT INTO T_ACCOUNT( ID, BALANCE, LAST_MODIFIED, PLAYER_ID) VALUES ( 3,0,current_date, 3 );
INSERT INTO T_ACCOUNT( ID, BALANCE, LAST_MODIFIED, PLAYER_ID) VALUES ( 4,0,current_date, 4 );
INSERT INTO T_ACCOUNT( ID, BALANCE, LAST_MODIFIED, PLAYER_ID) VALUES ( 5,0,current_date, 5 );

-- INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 1,100,0,current_date,'Credit' , 1 );
-- INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 2,100,0,current_date,'Credit' , 1 );
-- INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 3,100,0,current_date,'Credit' , 1 );
-- INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 4,100,0,current_date,'Credit' , 1 );
-- INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 5,100,0,current_date,'Credit' , 1 );
-- INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 6,100,0,current_date,'Credit' , 1 );
-- INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 7,100,0,current_date,'Credit' , 1 );
-- INSERT INTO T_TRANSACTION( ID, AMOUNT, BALANCE, LAST_MODIFIED, TYPE, PLAYER_ID) VALUES ( 8,100,0,current_date,'Credit' , 1 );

